# Generated by Django 6.0.4 on 2026-04-25 11:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark when handled in admin.')),
            ],
            options={
                'verbose_name': 'Contact inquiry',
                'verbose_name_plural': 'Contact inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('lechon', 'Lechon'), ('seafood', 'Seafood & Grill'), ('rice', 'Rice & Sides'), ('dessert', 'Desserts'), ('drinks', 'Drinks')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the home page featured grid (up to 6, plus backfill by newest).')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='The pleasure of variety on your plate', max_length=255)),
                ('about_lead', models.TextField(blank=True, help_text='Short intro for home/about snippet (supports line breaks).')),
                ('about_text', models.TextField(blank=True, help_text='Longer story for the About page.')),
                ('phone', models.CharField(default='09516811367', max_length=32)),
                ('email', models.EmailField(default='butuanlechon2022@gmail.com', max_length=254)),
                ('address', models.CharField(default='SM City Mall, 2nd Floor, J.C. Aquino Ave., Butuan City', max_length=255)),
                ('facebook_url', models.URLField(default='https://www.facebook.com/profile.php', help_text='Replace with your official Facebook page URL in Admin.', max_length=500, verbose_name='Facebook page URL')),
                ('maps_query', models.CharField(default='SM City Butuan', help_text='Used in the map embed; adjust if the pin is off.', max_length=200, verbose_name='Google Maps place query')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
