# Generated by Django 6.0.4 on 2026-04-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='about_lead',
            field=models.TextField(blank=True, default='Family-style Filipino favorites—crispy lechon, fresh seafood, and grill classics—served at SM City Mall, Butuan City.', help_text='Short intro for home/about snippet (supports line breaks).'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, default='Butuan Lechon & Seafoods Grill brings together the best of Mindanao hospitality and beloved Filipino flavors. From whole lechon celebrations to everyday seafood plates, our kitchen focuses on consistent quality, generous portions, and a warm dining experience for families and friends on the 2nd floor of SM City Butuan.', help_text='Longer story for the About page.'),
        ),
    ]
