# Generated by Django 6.0.4 on 2026-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_sitesettings_about_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(default='https://www.facebook.com/', help_text='Paste your official Facebook page URL in Admin (search “Butuan Lechon & Seafoods Grill” on Facebook if needed).', max_length=500, verbose_name='Facebook page URL'),
        ),
    ]
