# Generated by Django 6.0.4 on 2026-04-25 12:01

from django.db import migrations, models


def map_legacy_categories(apps, schema_editor):
    """Map pre-template category slugs to the new menu before applying new choices."""
    MenuItem = apps.get_model("restaurant", "MenuItem")
    for old, new in (
        ("lechon", "pork"),
        ("seafood", "fish_tuna"),
        ("rice", "rice"),
        ("dessert", "dessert"),
        ("drinks", "cold_drinks"),
    ):
        MenuItem.objects.filter(category=old).update(category=new)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_facebook_url_default'),
    ]

    operations = [
        migrations.RunPython(map_legacy_categories, noop),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('appetizer', 'Appetizer'), ('pork', 'Pork'), ('goat_meat', 'Goat meat'), ('chicken', 'Chicken'), ('value_meal', 'Value meal'), ('beef', 'Beef'), ('fish_tuna', 'Fish & tuna'), ('shrimp', 'Shrimp'), ('squid', 'Squid'), ('lapu_lapu', 'Lapu-lapu'), ('vegetables', 'Vegetables'), ('noodles', 'Noodles'), ('snacks', 'Snacks'), ('rice', 'Rice'), ('dessert', 'Dessert'), ('shakes', 'Shakes'), ('pitcher', 'Pitcher'), ('hot_drinks', 'Hot drinks'), ('cold_drinks', 'Cold drinks'), ('fruit_coolers', 'Fresh fruit coolers')], db_index=True, max_length=32),
        ),
    ]
